name: Install Dependencies

inputs:
    os:
        required: true

runs:
    using: composite
    steps:
        - name: update apt repositories
          if: inputs.os == 'ubuntu-latest'
          run: sudo apt-get update -y
        - name: install dependencies
          if: inputs.os == 'ubuntu-latest'
          run: >
            sudo apt-get install
            gstreamer-1.0
            libgstreamer1.0-dev
            libaravis-0.8-0
            libaravis-dev
            libgtkmm-3.0-dev
            libspdlog-dev
            libglib2.0-dev
            pkgconf
            libusb-1.0-0-dev
            libgstreamer-plugins-base1.0-dev
        - name: install dependencies
          if: inputs.os == 'windows-latest'
          uses: msys2/setup-msys2@v2
          with:
            install: >
              mingw-w64-x86_64-cmake 
              mingw-w64-x86_64-gtkmm3
              mingw-w64-x86_64-gstreamer
              mingw-w64-x86_64-gst-plugins-good
              mingw-w64-x86_64-gst-plugins-bad
              mingw-w64-x86_64-gst-plugins-ugly
              mingw-w64-x86_64-spdlog
              mingw-w64-x86_64-aravis
              mingw-w64-x86_64-aravis-gst
              mingw-w64-x86_64-ninja
              mingw-w64-x86_64-toolchain
              mingw-w64-x86_64-pkg-config